Feat/edit gmc2 johnny
Health-Education-England/tis-trainee-ui pull request #1100
Opened 2024-09-27 11:19 UTC by ReubenRobertsHEE

2024-10-01 14:43 UTC, ReubenRobertsHEE commented
@john12321 - is there anything else you would like covered test-wise? I'm guessing you can't review this (seeing as how much you've put into it), but any parting remarks or other concerns?

2024-10-01 15:01 UTC, john12321 commented
> @john12321 - is there anything else you would like covered test-wise? I'm guessing you can't review this (seeing as how much you've put into it), but any parting remarks or other concerns?

@ReubenRobertsHEE Just seen your e2e test commit. You are the Cypress Sensai 🥋. Was thinking about adding a gmcStatus loading state test to the Profile.cy.tsx but you've covered it much more realistically in the e2e test.

2024-10-01 15:27 UTC, Judge40 commented
Holy commit history Batman! 😂

2024-10-01 15:43 UTC, Judge40 requested changes

2024-10-01 15:43 UTC, Judge40 commented on cypress.config.ts
> +    baseUrl: "http://local.tis-selfservice.com",
I'm assuming this needs reverting

2024-10-01 15:43 UTC, Judge40 commented on cypress/e2e/profile/Profile.spec.ts
Is there any value in an additional test which explicitly verifies that an invalid value like `UNKNOWN` is retained if the user cancels the edit request, just to ensure we don't have any weird interactions with the validation?

2024-10-01 16:01 UTC, ReubenRobertsHEE commented on cypress/e2e/profile/Profile.spec.ts
Sure, I'll push one (and revert that e2e config change that crept in)

2024-10-02 07:30 UTC, Judge40 approved these changes

2024-10-02 08:19 UTC, merged